name: CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    build-and-test:
        runs-on: ubuntu-latest
        container:
            image: archlinux:latest
        strategy:
            matrix:
                compiler:
                    - {cc: gcc, cxx: g++}
                    - {cc: gcc, cxx: g++, stdlib_debug: true, sanitizer: address}
                    - {cc: clang, cxx: clang++}
                    - {cc: clang, cxx: clang++, stdlib: libc++, stdlib_debug: true, sanitizer: address}

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up C++ environment
              run: |
                pacman -Syu --noconfirm
                pacman -S --noconfirm git cmake base-devel ${{ matrix.compiler.cc == 'clang' && 'clang' || '' }} ${{ matrix.compiler.stdlib == 'libc++' && 'libc++ lld' || '' }}

            - name: Configure CMake
              run: >
                cmake -S tests -B build
                ${{ matrix.compiler.sanitizer && format('-DUSE_SANITIZER={0}', matrix.compiler.sanitizer) || '' }}
                ${{ matrix.compiler.stdlib && format('-DUSE_STD_LIB={0}', matrix.compiler.stdlib) || '' }}
                ${{ matrix.compiler.stdlib_debug && '-DUSE_STDLIB_DEBUG=true' || '' }}
              env:
                CC: ${{ matrix.compiler.cc }}
                CXX: ${{ matrix.compiler.cxx }}

            - name: Build project
              run: cmake --build build

            - name: Run tests
              run: cd build && ctest --output-on-failure
